{% set name = "IMAPClient" %}
{% set version = "2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 26ea995664fae3a88b878ebce2aff7402931697b86658b7882043ddb01b0e6ba

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - six

test:
  imports:
    - imapclient
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://imapclient.freshfoo.com/
  license: BSD-3-Clause
  license_file: COPYING
  license_family: BSD
  summary: Easy-to-use, Pythonic and complete IMAP client library
  doc_url: http://imapclient.readthedocs.io/
  dev_url: https://github.com/mjs/imapclient

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
