{% set name = "IMAPClient" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0578056b9fff5316516f460810fc8b485f6fd7e3f4203786c130e222007d63f3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - six

test:
  imports:
    - imapclient
  commands:
    - pip check
  requires: 
    - pip

about:
  home: http://imapclient.freshfoo.com/
  license: BSD-3-Clause
  license_file: COPYING
  license_family: BSD
  summary: 'Easy-to-use, Pythonic and complete IMAP client library'
  doc_url: http://imapclient.readthedocs.io/
  dev_url: https://github.com/mjs/imapclient

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
