travis:
  secure:
    BINSTAR_TOKEN: i4UDpozn5lNSl8kJ5h5Jd7Z26jAd+cbRMsfo4znv6ZhPRB7DPV5jeImCnqbJrPaVWTXcxUIKzkX6kLdsa+DNLObHoEDX+srGkI+rTagt70sQZ8l7SVXHEGpA0azn5hG9/dWi2emPDXLflqVOjCXKpe3wfB94+cX685q2CW+nSC8hSOQ+YcU7SxtJtvYHNxZyM0INGCWERo5fRN8rFiGn5Z+/HA2KFqSnA7ust9Shf38zc5UKhEXNRHrq+dCaEItA09u8JZpzht5LTsJZysu8fjP2N2C6YVvRhnbw+Iq+0kF0I7bHmSPUhUo8y3XZqEZwiv2L9I7je2BD3mJdegNNtVvqxypT6V0tgKOOmhWjaZ7ZGkZzdDPmbULO89x6l5254zqczUX4x1aQdt01EtSsWjbRM+kK4rNSRlAXSt9gnSbtj4RnPsTsitaUqu7ZwdAIWsHeeBfgJ5ZggPFG++kseH9z1H+J7GdgfMfFNFdjvUP9FohWbpzkDJDLzuoX28NKGx8xnKDCt+9n6s9Z4Z2CUQ28DgY7CO/YQn3NK9SZVwj2eCKXmP4PhtPbM35qUXxRLuwiezZZpxOXuobP4U/GR7MyQ8l3hNBWqWcIsDK/a7D/uxeSB7mP0p4fyiCJ8UY+rSiUR8XAEy/WTPHJCm+arxMtdO0akBZfYJD/hHAfdBs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
