travis:
  secure:
    BINSTAR_TOKEN: nGQnmh056sX8M6FjBXYopZJE/9UGr2ihETYU0vHv0JxYJvE4hSQm17gQ8P0bvucuSJxqy1SE9/qdfd/lf48BazkkxdA1u4LzCpLpZvfqvvmV8IbRmtL2br7SBs4IJPqZozUzLmRRy6qbglSaeedg3nEN39qPg23sKGmXDU2GLTM2wSKvB+iBFtBBqxVOAiH+8XHMBVom3o8SfSGr3hfx37zmDoLTGvRo2PFVmwN9EhJdufo8/+A221FWbHRF0NeYUREcKPJCvh2+WuS7PGVqUiBKQfYr6verIZs3IVazJaxOztnHwaZ4HUSK7NXG5MlbLCf0oL4Cq1qkouPlIM65FRkam4wYnxs9JA5C4Mfuz5mZXU6Muqbk8dLB2sNSipYygafvVzMfjJDtAmAa1No+m3BLaXu8ryWJDFuUBPJU9TjH3cu7TqPu/nY2gcCFUqD0G3aST6DsXqlol5KzchKjvOA9YBCwSlEaneT7Tl6z2YIniAC7WekxGffxCd/MCpej3+6glpxDcnLwyXXb5m8IURbkXvkRa4L+ig6zVfqQB6JhxZWTgYqGZIFVoi37QFVI7/aIwAiGKuG5DPgxgLcvocQtuaSOroXUyCAVTcJAYoCA+ak9x7BfvWDJqGUeiH7vr34U+omwvMf71xEqQ3TKRAfmFspiiINoXy6+RADiTZs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
